services:

  redis:
    image: "redis"
    volumes:
      - ./data:/data

  rss-telegram:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      REDIS_HOST: redis:6379
      BOT_TOKEN: YOUR_TOKEN
      RSS_INTERVAL: 30
    depends_on:
      - redis