name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./docker/Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image with tag
        if: startsWith(github.ref_name, 'v')
        run: |
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Create GitHub Release
        if: startsWith(github.ref_name, 'v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes
