name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./docker/Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image with tag
        if: startsWith(github.ref_name, 'v')
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Create GitHub Release
        if: startsWith(github.ref_name, 'v')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Changes in this release
            - Docker image pushed to registry: `${{ github.repository }}:${{ github.ref_name }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
